version: '3.3'

services:
  db: 
    container_name: postgres
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    restart: on-failure
    depends_on:
      - db
    build: .
    environment:
      LOCAL_STORAGE_PATH: "./books"
      PAGE_LENGTH: 6000
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db"
    ports:
      - "8000:8000"

volumes:
  postgres-data:
