//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::authors::Entity as Authors;
pub use super::books::Entity as Books;
pub use super::pages::Entity as Pages;
pub use super::payments::Entity as Payments;
pub use super::reads::Entity as Reads;
pub use super::users::Entity as Users;
